name: Build and Package WineHQ 8.12 on Ubuntu 22.04 (i386 and amd64)

on:
  push:
    branches:
      - master

jobs:
  build_i386:
    name: Build WineHQ 8.12 (i386)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: wine-8.12
        repository: wine-mirror/wine

    - name: Checkout the WineMUI code
      uses: actions/checkout@v3
      with:
        ref: master
        repository: cschuls/WineMUI
        path: WineMUI

    - name: Replace the file dll/kernelbase/loader.c
      run: |
        cp WineMUI/wine-devel/loader.c dlls/kernelbase/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token
      with:
        tag_name: v2206  # Ganti dengan tag yang sesuai dengan versi yang diunggah
        release_name: Release version 2206  # Nama rilis yang ingin ditampilkan

    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token

      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/*.7z
        asset_name: wsa-artifact.7z
        asset_content_type: application/x-7z-compressed
