name: Build and Package WineHQ on Ubuntu 22.04 (i386 and amd64)

on:
  push:
    branches:
      - master

# Define variables
env:
  WINE_VERSION: "8.15"

jobs:
  build_i386:
    name: Build WineHQ (i386)
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: wine-${{ env.WINE_VERSION }}
        repository: wine-mirror/wine

    - name: Checkout the WineMUI code
      uses: actions/checkout@v3
      with:
        ref: master
        repository: cschuls/WineMUI
        path: WineMUI

    - name: Replace the file dll/kernelbase/loader.c
      run: |
        cp WineMUI/wine-devel/loader.c dlls/kernelbase/

    - name: Set up environment (i386)
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update

    - name: Build WineHQ (i386)
      run: |
        ./configure

    - name: Package build artifacts
      run: |
        7z a winehq-${{ env.WINE_VERSION }}_i386.7z *

    - name: Package build KernelBase artifacts
      run: |
        7z a kernelbase_i386.7z dlls/kernelbase/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: winehq-${{ env.WINE_VERSION }}_i386.7z
        path: winehq-${{ env.WINE_VERSION }}_i386.7z

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token
      with:
        tag_name: v${{ env.WINE_VERSION }}  # Menggunakan variabel RELEASE_VERSION
        release_name: Release version ${{ env.WINE_VERSION }}  # Menggunakan variabel RELEASE_VERSION

    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./kernelbase_i386.7z
        asset_name: kernelbase_i386.7z  # Menggunakan variabel RELEASE_VERSION
        asset_content_type: application/x-7z-compressed

  build_amd64:
    name: Build WineHQ (amd64)
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: wine-${{ env.WINE_VERSION }}
        repository: wine-mirror/wine

    - name: Checkout the WineMUI code
      uses: actions/checkout@v3
      with:
        ref: master
        repository: cschuls/WineMUI
        path: WineMUI

    - name: Replace the file dll/kernelbase/loader.c
      run: |
        cp WineMUI/wine-devel/loader.c dlls/kernelbase/

    - name: Set up environment (amd64)
      run: |
        sudo apt-get update

    - name: Build WineHQ (amd64)
      run: |
        ./configure --enable-win64

    - name: Package build artifacts
      run: |
        7z a winehq-${{ env.WINE_VERSION }}_amd64.7z *

    - name: Package build KernelBase artifacts
      run: |
        7z a kernelbase_amd64.7z dlls/kernelbase/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: winehq-${{ env.WINE_VERSION }}_amd64.7z
        path: winehq-${{ env.WINE_VERSION }}_amd64.7z
        
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token
      with:
        tag_name: v${{ env.WINE_VERSION }}  # Menggunakan variabel RELEASE_VERSION
        release_name: Release version ${{ env.WINE_VERSION }}  # Menggunakan variabel RELEASE_VERSION

    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./kernelbase_amd64.7z
        asset_name: kernelbase_amd64.7z  # Menggunakan variabel RELEASE_VERSION
        asset_content_type: application/x-7z-compressed
