name: Build and Package WineHQ 8.12 on Ubuntu 22.04 (i386 and amd64)

on:
  push:
    branches:
      - master

jobs:
  build_i386:
    name: Build WineHQ 8.12 (i386)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: wine-8.12
        repository: wine-mirror/wine

    - name: Checkout the WineMUI code
      uses: actions/checkout@v3
      with:
        ref: master
        repository: cschuls/WineMUI
        path: WineMUI

    - name: Replace the file dll/kernelbase/loader.c
      run: |
        cp WineMUI/wine-devel/loader.c dlls/kernelbase/

    - name: Set up environment (i386)
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y libgcc-s1:i386 libstdc++6:i386 libc6:i386 libicu70:i386
        sudo apt-get install -y build-essential libc6-dev-i386 gcc-multilib g++-multilib
        sudo apt-get install -y libasound2-dev:i386 libpulse-dev:i386 libdbus-1-dev:i386 libfontconfig-dev:i386 libfreetype-dev:i386 libgnutls28-dev:i386 libgl-dev:i386 libunwind-dev:i386 libx11-dev:i386 libxcomposite-dev:i386 libxcursor-dev:i386 libxfixes-dev:i386 libxi-dev:i386 libxrandr-dev:i386 libxrender-dev:i386 libxext-dev:i386 libgstreamer1.0-dev:i386 libgstreamer-plugins-base1.0-dev:i386 libosmesa6-dev:i386 libsdl2-dev:i386 libudev-dev:i386 libvulkan-dev:i386 libcapi20-dev:i386 libcups2-dev:i386 libgphoto2-dev:i386 libsane-dev:i386 libkrb5-dev:i386 samba-dev:i386 ocl-icd-opencl-dev:i386 libpcap-dev:i386 libusb-1.0-0-dev:i386
        sudo apt-get install -y libgl1-mesa-dev:i386 libglu1-mesa-dev:i386
        sudo apt-get install -y wine32-development-tools
        sudo apt-get install -y devscripts
        sudo apt-get install -y p7zip-full

    - name: Build WineHQ 8.12 (i386)
      run: |
        ./configure
        make
        sudo make install

    - name: Upload Kernelbase artifacts
      uses: actions/upload-artifact@v3
      with:
        name: KernelbaseMUI(x86)
        path: dlls/kernelbase/
